import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/thesis')({
  component: ThesisPage,
})

const chapters = [
  {
    num: '01',
    title: 'The Problem of Authored Emergence',
    summary: 'Traditional narrative design in games operates on a branching tree model — a finite set of authored states connected by player choices. This model breaks under the weight of procedural systems. When the world is generated, when NPC behavior is emergent, when player paths diverge at a combinatorial scale, the authored tree becomes a authored forest — too large to write, too constrained to feel alive. This chapter establishes the tension between author intent and systemic emergence as the central problem of procedural narrative design.',
  },
  {
    num: '02',
    title: 'Grammars for Story: Rule-Based Narrative Systems',
    summary: 'Examining existing computational approaches to narrative generation — from classic story grammars (Propp, Greimas) to modern drama managers (Façade, Left 4 Dead\'s Director). The chapter argues that rule-based systems can encode authorial intent without requiring explicit content for every possible state, if the rules operate on story structure rather than story content.',
  },
  {
    num: '03',
    title: 'Constraint Propagation as Narrative Curation',
    summary: 'A formal model for narrative constraint propagation: the claim that interesting stories can be generated by propagating hard and soft constraints across a temporal graph of possible events. Hard constraints enforce logical and tonal consistency; soft constraints bias toward dramatic structure (Freytag\'s pyramid, three-act form). The model is demonstrated with a working prototype.',
  },
  {
    num: '04',
    title: 'Empirical Study: Player Perception of Authored vs. Generated Narrative',
    summary: 'Results from a 120-participant study comparing player perception of hand-authored vs. constraint-generated narrative sequences. Participants could not reliably distinguish generated from authored sequences above chance after two play sessions. The study suggests that structural coherence matters more to perceived narrative quality than content specificity.',
  },
  {
    num: '05',
    title: 'Toward a Practice: Design Patterns for Procedural Narrative',
    summary: 'Distilling the research into actionable design patterns for game developers: the Narrative Seed pattern, the Constraint Stack, the Dramatic Arc Enforcer, and the Memory-Weighted Event Selector. Each pattern is illustrated with pseudocode and game design examples.',
  },
]

function ThesisPage() {
  return (
    <div className="min-h-screen page-enter">
      {/* Header */}
      <div
        className="px-4 sm:px-6 lg:px-8 py-16"
        style={{
          borderBottom: '1px solid rgba(255,0,128,0.1)',
          background: 'radial-gradient(ellipse at 70% 30%, rgba(255,0,128,0.04) 0%, transparent 60%)',
        }}
      >
        <div className="max-w-7xl mx-auto">
          <div className="font-mono-game text-xs mb-3" style={{ color: 'var(--neon-magenta)' }}>
            {'// SECTION_04 :: ACADEMIC.RESEARCH'}
          </div>
          <h1 className="font-heading text-4xl sm:text-6xl font-black mb-4" style={{ color: 'white' }}>
            THESIS
          </h1>
          <div
            className="inline-block font-heading text-lg font-bold mb-6 px-4 py-2"
            style={{
              border: '1px solid rgba(255,0,128,0.3)',
              color: 'var(--neon-magenta)',
              background: 'rgba(255,0,128,0.05)',
            }}
          >
            Procedural Narrative Systems in Open-World Games:<br />
            <span style={{ color: 'rgba(255,255,255,0.7)', fontWeight: 400, fontSize: '0.9rem' }}>
              A Constraint-Based Approach to Emergent Storytelling
            </span>
          </div>
          <div className="flex flex-wrap gap-6 font-mono-game text-xs" style={{ color: 'rgba(255,255,255,0.4)' }}>
            <span>DigiPen Institute of Technology // 2020</span>
            <span>Advisor: Dr. Sarah Chen</span>
            <span>Defense: May 12, 2020</span>
          </div>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        {/* Abstract */}
        <section className="mb-16">
          <div className="flex items-center gap-4 mb-8">
            <h2 className="section-header text-sm" style={{ color: 'rgba(255,0,128,0.8)' }}>
              ABSTRACT
            </h2>
            <div className="flex-1 h-px" style={{ background: 'linear-gradient(90deg, rgba(255,0,128,0.4), transparent)' }} />
          </div>

          <div className="terminal-box" style={{ borderLeftColor: 'var(--neon-magenta)', borderColor: 'rgba(255,0,128,0.2)' }}>
            <p className="leading-relaxed" style={{ color: 'rgba(255,255,255,0.7)' }}>
              Modern open-world games generate vast spatial environments procedurally, yet their narratives remain hand-authored — a fundamental mismatch that limits the depth of player agency. This thesis proposes a constraint-based model for procedural narrative generation that preserves authorial intent while enabling combinatorial story diversity. The model encodes narrative requirements as hard constraints (logical consistency, causal validity) and soft constraints (dramatic arc preference, tonal coherence) propagated across a temporal event graph. A 120-participant empirical study demonstrates that sequences generated by the proposed system are perceptually indistinguishable from hand-authored sequences by players after two sessions, suggesting that structural coherence is the primary determinant of perceived narrative quality. The thesis concludes with a set of design patterns enabling practitioners to implement constraint-based narrative in commercial game development pipelines.
            </p>
          </div>
        </section>

        {/* Key Contributions */}
        <section className="mb-16">
          <div className="flex items-center gap-4 mb-8">
            <h2 className="section-header text-sm" style={{ color: 'rgba(255,0,128,0.8)' }}>
              KEY_CONTRIBUTIONS
            </h2>
            <div className="flex-1 h-px" style={{ background: 'linear-gradient(90deg, rgba(255,0,128,0.4), transparent)' }} />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[
              {
                label: 'Formal Model',
                desc: 'A constraint propagation model for narrative event graphs with proof of convergence under reasonable assumptions.',
              },
              {
                label: 'Empirical Study',
                desc: 'First controlled study comparing player perception of authored vs. constraint-generated narrative in an interactive context.',
              },
              {
                label: 'Design Patterns',
                desc: '5 actionable design patterns for implementing procedural narrative in commercial game development workflows.',
              },
              {
                label: 'Open Prototype',
                desc: 'A Unity-integrated prototype system demonstrating the model in a playable environment, published open-source.',
              },
            ].map((item) => (
              <div
                key={item.label}
                className="p-5"
                style={{
                  border: '1px solid rgba(255,0,128,0.2)',
                  background: 'rgba(255,0,128,0.03)',
                  clipPath: 'polygon(0 0, calc(100% - 12px) 0, 100% 12px, 100% 100%, 0 100%)',
                }}
              >
                <div className="font-heading text-sm font-bold mb-2" style={{ color: 'var(--neon-magenta)' }}>
                  {item.label}
                </div>
                <p className="text-sm" style={{ color: 'rgba(255,255,255,0.55)', fontFamily: 'Rajdhani, sans-serif', fontWeight: 500 }}>
                  {item.desc}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* Chapters */}
        <section className="mb-16">
          <div className="flex items-center gap-4 mb-8">
            <h2 className="section-header text-sm" style={{ color: 'rgba(255,0,128,0.8)' }}>
              TABLE_OF_CONTENTS
            </h2>
            <div className="flex-1 h-px" style={{ background: 'linear-gradient(90deg, rgba(255,0,128,0.4), transparent)' }} />
          </div>

          <div className="space-y-4">
            {chapters.map((chapter) => (
              <div
                key={chapter.num}
                className="game-card game-card-magenta p-6 flex gap-5"
                style={{ border: '1px solid rgba(255,0,128,0.12)' }}
              >
                <div
                  className="font-heading text-3xl font-black flex-shrink-0 leading-none"
                  style={{ color: 'rgba(255,0,128,0.2)' }}
                >
                  {chapter.num}
                </div>
                <div>
                  <h3 className="font-heading text-base font-bold mb-2" style={{ color: 'white' }}>
                    {chapter.title}
                  </h3>
                  <p className="text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.5)', fontFamily: 'Rajdhani, sans-serif', fontWeight: 500 }}>
                    {chapter.summary}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Outcome */}
        <div
          className="p-6 text-center"
          style={{
            border: '1px solid rgba(255,0,128,0.3)',
            background: 'rgba(255,0,128,0.05)',
          }}
        >
          <div className="font-mono-game text-xs mb-2" style={{ color: 'var(--neon-magenta)' }}>
            RESULT
          </div>
          <p className="font-heading text-lg" style={{ color: 'white' }}>
            Best Technical Achievement — DigiPen Senior Capstone 2020
          </p>
          <p className="font-mono-game text-xs mt-2" style={{ color: 'rgba(255,255,255,0.4)' }}>
            Full PDF available upon request
          </p>
        </div>
      </div>
    </div>
  )
}
