/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as StudiesRouteImport } from './routes/studies'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudiesIndexRouteImport } from './routes/studies/index'
import { Route as StudiesSlugRouteImport } from './routes/studies/$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesRoute = StudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesIndexRoute = StudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudiesRoute,
} as any)
const StudiesSlugRoute = StudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StudiesRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/studies': typeof StudiesRouteWithChildren
  '/thoughts': typeof ThoughtsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/studies/$slug': typeof StudiesSlugRoute
  '/studies/': typeof StudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/thoughts': typeof ThoughtsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/studies/$slug': typeof StudiesSlugRoute
  '/studies': typeof StudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/studies': typeof StudiesRouteWithChildren
  '/thoughts': typeof ThoughtsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/studies/$slug': typeof StudiesSlugRoute
  '/studies/': typeof StudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/projects'
    | '/resume'
    | '/studies'
    | '/thoughts'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/studies/$slug'
    | '/studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/projects'
    | '/resume'
    | '/thoughts'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/studies/$slug'
    | '/studies'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/projects'
    | '/resume'
    | '/studies'
    | '/thoughts'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/studies/$slug'
    | '/studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  StudiesRoute: typeof StudiesRouteWithChildren
  ThoughtsRoute: typeof ThoughtsRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies': {
      id: '/studies'
      path: '/studies'
      fullPath: '/studies'
      preLoaderRoute: typeof StudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies/': {
      id: '/studies/'
      path: '/'
      fullPath: '/studies/'
      preLoaderRoute: typeof StudiesIndexRouteImport
      parentRoute: typeof StudiesRoute
    }
    '/studies/$slug': {
      id: '/studies/$slug'
      path: '/$slug'
      fullPath: '/studies/$slug'
      preLoaderRoute: typeof StudiesSlugRouteImport
      parentRoute: typeof StudiesRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface StudiesRouteChildren {
  StudiesSlugRoute: typeof StudiesSlugRoute
  StudiesIndexRoute: typeof StudiesIndexRoute
}

const StudiesRouteChildren: StudiesRouteChildren = {
  StudiesSlugRoute: StudiesSlugRoute,
  StudiesIndexRoute: StudiesIndexRoute,
}

const StudiesRouteWithChildren =
  StudiesRoute._addFileChildren(StudiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResumeRoute: ResumeRoute,
  StudiesRoute: StudiesRouteWithChildren,
  ThoughtsRoute: ThoughtsRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
